# Generated by Django 5.0.1 on 2024-01-07 14:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0005_alter_actors_latest_movie_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='academy_awards',
            field=models.SmallIntegerField(
                default=' ',
                null=True,
                validators=[django.core.validators.MinValueValidator(
                    0), django.core.validators.MaxValueValidator(11)],
            ),
        ),
        migrations.AlterField(
            model_name='movies',
            name='category',
            field=models.CharField(default=' ', max_length=200, null=True),
        ),
    ]
